### ISSUE TITLE
User guide on exporting plots

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gos#104]
We have the `.save()` function explained on the doc under [API Reference](https://gosling-lang.github.io/gos/user_guide/generated/toplevel/gosling.View.html), but it is quite hidden to users and does not provide detailed explanations and examples. I think we need to add a dedicated page or section that describes ways to export Gos plots (e.g., html, json). Maybe we can add a section near the Local Data?:

<img width="263" alt="Screen Shot 2022-08-17 at 09 18 12" src="https://user-images.githubusercontent.com/9922882/185144278-cc04e3aa-49b3-4ff0-a745-2c55bb36e555.png">

Related tweet: https://twitter.com/sminot/status/1559746056669126657?s=21&t=yCLH8vli7kbjDf8foZhy5g

**Comment by sehilyi** [comment]
Btw, do we already support png/pdf exports?

**Comment by manzt** [comment]
Agreed! Perhaps we can draw inspiration from: https://altair-viz.github.io/user_guide/saving_charts.html

> Btw, do we already support png/pdf exports?

Not at the moment. This is very tricky to do from the Python side because it requires talking to an **active** Gosling API. This is a feature we could add to `gosling-widget` since Jupyter Widgets provide JS <> Python communication, but otherwise I'm not sure it would be possible. 

I think having a dropdown for every vis in `gosling.embed` like vega-lite would be preferable. 

![image](https://user-images.githubusercontent.com/24403730/185150337-455c6b3f-87ac-476f-b8f8-c56dd5042017.png)

**Comment by sehilyi** [comment]
Looks like showing the dropdown menu seems to be a more reasonable choice. Would the menu (added to `gosling.embed`) consistently be shown in the grosling as well?
