### ISSUE TITLE
Plotting Single Co-ordinate BED file on custom assembly

### ISSUE THREAD

**Issue by Gr1m3y** [gosling-lang/gos#120]
Hi,

First, thanks for the great work! I am really liking the layout of Gosling so far! 

I am having an issue plotting some data. I have a microbial assembly with two chromosomes and a tsv file with three columns: chromosome, position, value (the file does not have a header). I want to plot the values along each chromosome, so have code like this:

```
data = gos.csv(
    "../data/06_coverage/23b_coverage.bed",
    separator="\t",
    headerNames=["chrom", "position", "value"],
    chromosomeField="chrom",
    genomicFields=["position"]
)

gos.Track(data).mark_bar().encode(
    x=gos.X("position:G"),
    y=gos.Y("value:Q", axis="left"),
).view(
    assembly=[
        ("NC_012345.1", 1_234_567),
        ("NC_012346.1", 45000)
    ]
)
```

When I run the plot, I just get a blank canvas with the chromosome labels/positions along the top, but no data is showing up. I am not sure what I am missing here. Does the file have to have two coordinates for each feature? 

Thanks in advance for the help! I hope this is not something obvious that I am missing.

Keep up the great work! Excited to see this tool continue to develop!

**Comment by sehilyi** [comment]
Hi @Gr1m3y, thank you for reaching out!

The code looks good to me. If you see the empty track, I think Gosling was not able to load data to render. One possibility is that the URL to the data is incorrect. You can confirm this, for example, by opening the [Console tab of Chrome Developer Tools](https://balsamiq.com/support/faqs/browserconsole/#:~:text=Google%20Chrome,-To%20open%20the&text=You%20can%20also%20use%20Option,to%20select%20the%20Console%20tab.) and finding related errors, e.g., `GET https://localhost:8080/[filename].bed net::ERR_ABORTED 500`.

Another possibility is that `csv()` does not properly parse the contents of the BED file due to incorrect parameters. For example, the following data I created is correctly displayed on Gos.

```
NC_012345.1	1	1
NC_012345.1	10000	10000
NC_012345.1	1000000	1000000
NC_012346.1	1	1
NC_012346.1	100	100
NC_012346.1	1000	1000
```

<img width="1011" alt="Screenshot 2022-11-30 at 09 03 15" src="https://user-images.githubusercontent.com/9922882/204818053-d9b351bb-a2e3-42c1-a305-99a4cb4ddcf9.png">

> Does the file have to have two coordinates for each feature?

Nope. Single coordinate should also work.

Let me know if you still cannot address the issue!

**Comment by Gr1m3y** [comment]
Hi @sehilyi 

I still seem to be having issues. I am wondering if it has to do with the amount of data? Is there a practical limit on how many rows of data Gosling can handle? Beyond that, I am not certain what it could be. I did not see any errors in loading the data, and to verify, I tried to set everything up exactly how you have it. I will try to experiment with some smaller datasets to see what happens.

**Comment by manzt** [comment]
Hi, just going through old issues. We haven't done any benchmarking, but yes, very large tabular files may be challenging for Gosling to handle. There is a memory limit in the web browser (4GB), which if exceeded can cause issues. If you have any more information about the data I could try to help debug further.

**Comment by cademirch** [comment]
Hi, I am trying to use gos to visualize a local bed file exactly like the OP, and am also having trouble. I am working on a local python notebook and the visualization is just a blank canvas.

My code:
```
import gosling as gos

data = gos.csv(
    url="./jw18_NC_002978.6_cov.bed",
    headerNames=['chrom', 'position', 'value'],
    chromosomeField="chrom",
    genomicFields=["position"],
    
    separator="\t",
)
gos.Track(data).mark_bar().encode(
    x=gos.X("position:G"),
    y=gos.Y("value:Q", axis="left"),
).view(
    assembly=[
        ("NC_002978.6", 1267782),
    ]
)
```

And the bed file looks like this:
```
NC_002978.6  0     0
NC_002978.6  3428  1
NC_002978.6  3439  2
NC_002978.6  3441  6
NC_002978.6  3446  8
NC_002978.6  3451  12
NC_002978.6  3454  16
NC_002978.6  3462  17
NC_002978.6  3463  21
NC_002978.6  3468  22
```

Would appreciate any advice! Thank you.
