### ISSUE TITLE
Loading data from URL isn't always a success 

### ISSUE THREAD

**Issue by cbattist** [gosling-lang/gos#129]
Hi,
I'm trying to plot some data and having trouble loading these data from CSV files using URL. My visualization is generated nicely with local data, but I want to be able to share it. According to Gosling documentation I should be able to load my data through URL directly without an Higlass server. So, I made a few tests and it turn out that I don't succeed to load my data from my server, while I do when I load the data from Dropbox. I have no clue of why or how to handle it, and I haven't find any documentation of how Gosling load data from URL or if there are any specific requirements to do so. [Here](https://data-dataref.ifremer.fr/bioinfo/ifremer/sebimer/tools/MopSeq-DB/data/www/to_url_files/GCF_012395215-chr1.csv) is an example of the data I'm trying to load. Maybe you have an idea of how to make it work, or you can enlighten me of how Gosling function? 

Thanks a lot for your work developing this tool, and I hope you can help me with my issue.
Cheers

**Comment by manzt** [comment]
Thank you for opening an issue and trying out Gos! 

Since you mentioned that you are self-hosting the data, I'm guessing this is an issue with CORS (cross origin resource sharing). CORS is an HTTP-header based mechanism that allows a server to indicate any origins (the requesting webpage) other than its own from which a browser should permit loading resources. This is a common issue for loading data in _all_ web-based tools, which is why we don't have dedicated documentation (although maybe we should have some pointers!).

It's likely that you need to configure a CORS policy on your server to allow Gosling to access the data. Both Dropbox and local data (with Python Gos) work because they serve the data with CORS enabled by default.

Unfortunately, I'm not sure how your server is implemented, so you'll need to look into the documentation specific to your server for adding a CORS policy. Once you've configured the CORS policy, you should be able to load your data with Gosling.

To test if your server is configured correctly, you can open your browser console or use a tool like [Observable notebooks](https://observablehq.com/) to make a fetch request to your server. If you successfully get a response, your data should work with Gosling.

For example, with the data your shared:

<img alt="image" src="https://user-images.githubusercontent.com/24403730/234608700-37a24228-5bde-4e64-8d98-0558b98036aa.png">


In the console I can see a CORs error.

**Comment by cbattist** [comment]
Indeed, with the modification of the CORS configuration, it works well.
Thank you very much for your help and quick response!

**Comment by manzt** [comment]
Great!
